# Generated by Django 4.2.27 on 2025-12-24 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('masked_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('SUPPORT', 'Customer Support'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('FINANCE', 'Finance'), ('DESIGN', 'Design'), ('OTHER', 'Other')], max_length=20)),
                ('experience_years', models.PositiveIntegerField()),
                ('current_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('religion', models.CharField(blank=True, choices=[('HINDU', 'Hindu'), ('MUSLIM', 'Muslim'), ('CHRISTIAN', 'Christian'), ('SIKH', 'Sikh'), ('BUDDHIST', 'Buddhist'), ('JAIN', 'Jain'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnlockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_used', models.PositiveIntegerField(default=10)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('hr_user', models.ForeignKey(limit_choices_to={'role': 'hr'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('hr_user', 'candidate')},
            },
        ),
    ]
