# Generated by Django 6.0 on 2025-12-31 13:50

import apps.candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='filter_icons/', validators=[apps.candidates.models.validate_icon_file]),
        ),
    ]
