# Generated by Django 6.0 on 2026-01-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
