# Generated by Django 4.2.27 on 2025-12-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='video_intro',
            field=models.FileField(blank=True, upload_to='video_intros/'),
        ),
    ]
