# Generated by Django 4.2.27 on 2025-12-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_video_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='video_intro',
            field=models.FileField(blank=True, null=True, upload_to='video_intros/'),
        ),
    ]
