# Generated by Django 6.0 on 2026-01-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_filtercategory_icon'),
        ('candidates', '0003_candidate_education_details'),
    ]

    operations = [
    ]
