# Generated by Django 6.0 on 2026-01-02 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_merge_20260102_1105'),
        ('recruiters', '0002_remove_hrprofile_credits_balance_hrprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFollowup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('followup_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='candidates.candidate')),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_followups', to='recruiters.hrprofile')),
            ],
            options={
                'ordering': ['followup_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidates.candidate')),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_notes', to='recruiters.hrprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
