# Generated by Django 6.0 on 2026-01-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_remove_candidate_work_experience_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='education',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='education_details',
        ),
    ]
