# Generated by Django 6.0 on 2026-01-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_remove_candidate_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteroption',
            name='bento_grid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='dashboard_display',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='inner_filter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
