# Generated by Django 6.0 on 2026-01-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_filteroption_bento_grid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteroption',
            name='bento_grid',
        ),
        migrations.RemoveField(
            model_name='filteroption',
            name='dashboard_display',
        ),
        migrations.RemoveField(
            model_name='filteroption',
            name='inner_filter',
        ),
        migrations.AddField(
            model_name='filtercategory',
            name='bento_grid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filtercategory',
            name='dashboard_display',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filtercategory',
            name='inner_filter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
