# Generated by Django 6.0 on 2026-01-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_remove_filteroption_bento_grid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_step',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
