# Generated by Django 6.0 on 2026-01-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_candidate_is_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='joining_availability',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('NOTICE_PERIOD', 'Notice Period')], default='IMMEDIATE', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
