# Generated by Django 6.0 on 2026-01-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_candidate_joining_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='full_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
