# Generated by Django 6.0 on 2026-01-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_remove_candidate_full_name_candidate_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='career_objective',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='street_address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
