# Generated by Django 6.0 on 2026-01-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_alter_candidate_current_ctc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='current_ctc',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='expected_ctc',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
