# Generated by Django 6.0 on 2026-01-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_remove_candidate_current_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='step1_completed',
            field=models.BooleanField(default=False, help_text='Basic information filled'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='step1_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='step2_completed',
            field=models.BooleanField(default=False, help_text='Work experience added'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='step2_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='step3_completed',
            field=models.BooleanField(default=False, help_text='Education information added'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='step3_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='step4_completed',
            field=models.BooleanField(default=False, help_text='Profile fully completed'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='step4_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
