# Generated by Django 6.0 on 2026-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_candidate_step1_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_available_for_hiring',
            field=models.BooleanField(default=True, help_text='Is candidate currently available for hiring opportunities'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_availability_update',
            field=models.DateTimeField(blank=True, help_text='Last time candidate updated their availability status', null=True),
        ),
    ]
