# Generated by Django 6.0 on 2026-01-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_add_availability_for_hiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='declaration_agreed_at',
            field=models.DateTimeField(blank=True, help_text='When candidate agreed to declaration', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='has_agreed_to_declaration',
            field=models.BooleanField(default=False, help_text='Candidate agreed to declaration'),
        ),
    ]
