# Generated by Django 6.0 on 2026-01-19 12:58

import apps.candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_candidate_declaration_agreed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteroption',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='filter_option_icons/', validators=[apps.candidates.models.validate_icon_file]),
        ),
    ]
