# Generated by Django 6.0 on 2026-01-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_filteroption_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringAvailabilityUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name for admin reference', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time')),
                ('title', models.CharField(default='Are you still available for hiring?', max_length=200)),
                ('message', models.TextField(default="Please confirm if you're still open to new job opportunities.")),
                ('button_layout', models.CharField(choices=[('column', 'Column (Vertical Stack)'), ('row', 'Row (Horizontal)')], default='column', max_length=10)),
                ('background_type', models.CharField(choices=[('color', 'Solid Color'), ('image', 'Image'), ('gradient', 'Gradient')], default='color', max_length=10)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Hex color code (e.g., #FFFFFF)', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hiring_availability_bg/')),
                ('gradient_start_color', models.CharField(default='#FFFFFF', help_text='Gradient start color', max_length=7)),
                ('gradient_end_color', models.CharField(default='#F5F5F5', help_text='Gradient end color', max_length=7)),
                ('icon_type', models.CharField(default='work_outline_rounded', help_text='Material Icon name', max_length=50)),
                ('icon_size', models.FloatField(default=60.0)),
                ('icon_color', models.CharField(default='#4CAF50', help_text='Icon color hex code', max_length=7)),
                ('icon_background_color', models.CharField(default='#4CAF5019', help_text='Icon background with opacity', max_length=9)),
                ('show_icon', models.BooleanField(default=True)),
                ('title_font_size', models.FloatField(default=24.0)),
                ('title_font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('w600', 'Semi Bold'), ('w700', 'Bold'), ('w800', 'Extra Bold')], default='bold', max_length=20)),
                ('title_color', models.CharField(default='#000000', max_length=7)),
                ('title_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('message_font_size', models.FloatField(default=16.0)),
                ('message_font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('w500', 'Medium'), ('w600', 'Semi Bold')], default='normal', max_length=20)),
                ('message_color', models.CharField(default='#757575', max_length=7)),
                ('message_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('primary_button_text', models.CharField(default="Yes, I'm Available", max_length=100)),
                ('primary_button_bg_color', models.CharField(default='#4CAF50', max_length=7)),
                ('primary_button_text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('primary_button_font_size', models.FloatField(default=18.0)),
                ('primary_button_font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('w500', 'Medium'), ('w600', 'Semi Bold'), ('w700', 'Bold')], default='w600', max_length=20)),
                ('primary_button_height', models.FloatField(default=56.0)),
                ('primary_button_border_radius', models.FloatField(default=12.0)),
                ('secondary_button_text', models.CharField(default='No, Not Available', max_length=100)),
                ('secondary_button_bg_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('secondary_button_text_color', models.CharField(default='#616161', max_length=7)),
                ('secondary_button_border_color', models.CharField(default='#BDBDBD', max_length=7)),
                ('secondary_button_font_size', models.FloatField(default=18.0)),
                ('secondary_button_font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('w500', 'Medium'), ('w600', 'Semi Bold'), ('w700', 'Bold')], default='w600', max_length=20)),
                ('secondary_button_height', models.FloatField(default=56.0)),
                ('secondary_button_border_radius', models.FloatField(default=12.0)),
                ('spacing_between_buttons', models.FloatField(default=16.0, help_text='Space between buttons in pixels')),
                ('content_padding_horizontal', models.FloatField(default=24.0)),
                ('content_padding_vertical', models.FloatField(default=32.0)),
                ('extra_content', models.JSONField(blank=True, help_text="Additional content sections in JSON format. Example: [{'type': 'text', 'content': 'Extra info', 'position': 'top'}]", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hiring Availability UI Configuration',
                'verbose_name_plural': 'Hiring Availability UI Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
