# Generated by Django 6.0 on 2026-01-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_hiringavailabilityui'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringavailabilityui',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload custom icon/image (only for upload source)', null=True, upload_to='hiring_availability_icons/'),
        ),
        migrations.AddField(
            model_name='hiringavailabilityui',
            name='icon_source',
            field=models.CharField(choices=[('material', 'Material Icon (Built-in)'), ('upload', 'Upload Custom Icon/Image')], default='material', help_text='Choose icon source', max_length=10),
        ),
        migrations.AlterField(
            model_name='hiringavailabilityui',
            name='icon_color',
            field=models.CharField(default='#4CAF50', help_text='Icon color hex code (only for material icons)', max_length=7),
        ),
        migrations.AlterField(
            model_name='hiringavailabilityui',
            name='icon_size',
            field=models.FloatField(default=60.0, help_text='Icon size in pixels'),
        ),
        migrations.AlterField(
            model_name='hiringavailabilityui',
            name='icon_type',
            field=models.CharField(default='work_outline_rounded', help_text='Material Icon name (only for material source)', max_length=50),
        ),
    ]
