# Generated by Django 6.0 on 2026-01-21 11:50

import apps.candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_hiringavailabilityui_icon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringavailabilityui',
            name='icon_image',
            field=models.FileField(blank=True, help_text='Upload custom icon/image - supports PNG, JPG, JPEG, SVG (only for upload source)', null=True, upload_to='hiring_availability_icons/', validators=[apps.candidates.models.validate_icon_file]),
        ),
    ]
