# Generated by Django 6.0 on 2026-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0023_alter_hiringavailabilityui_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringavailabilityui',
            name='content_vertical_alignment',
            field=models.CharField(choices=[('top', 'Top - Content starts from top'), ('center', 'Center - Content centered vertically'), ('bottom', 'Bottom - Content aligned to bottom')], default='center', help_text='Vertical position of all content in the screen', max_length=10),
        ),
    ]
