# Generated by Django 6.0 on 2026-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0024_hiringavailabilityui_content_vertical_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='gap_reason',
            field=models.TextField(blank=True, help_text='Reason for career gap', null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='is_gap_period',
            field=models.BooleanField(default=False, help_text='True if this is a career gap'),
        ),
    ]
