# Generated by Django 6.0 on 2026-01-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0025_candidate_work_experience_details_and_more'),
        ('candidates', '0025_workexperience_gap_reason_and_more'),
    ]

    operations = [
    ]
