# Generated by Django 6.0 on 2026-01-24 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0026_merge_20260124_1131'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filteroption',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this option was approved', null=True),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this option', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_filter_options', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='is_approved',
            field=models.BooleanField(default=True, help_text="Admin approval for custom 'Other' options"),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When this option was submitted', null=True),
        ),
        migrations.AddField(
            model_name='filteroption',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this custom option', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_filter_options', to=settings.AUTH_USER_MODEL),
        ),
    ]
