# Generated by Django 6.0 on 2026-01-24 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0027_filteroption_approved_at_filteroption_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Tip title', max_length=200)),
                ('subtitle', models.CharField(help_text='Short description', max_length=300)),
                ('icon_type', models.CharField(default='photo_camera_outlined', help_text='Material Icon name', max_length=50)),
                ('instructions', models.JSONField(help_text="Array of instruction steps. Example: ['Step 1', 'Step 2']")),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order to display tips')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this tip')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile Tip',
                'verbose_name_plural': 'Profile Tips',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
