# Generated by Django 6.0 on 2026-01-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0026_merge_20260124_1144'),
        ('candidates', '0028_profiletip'),
    ]

    operations = [
    ]
