# Generated by Django 6.0 on 2026-01-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0029_merge_0026_merge_20260124_1144_0028_profiletip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFilterOption',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Location',
                'verbose_name_plural': '📋 Pending Locations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('candidates.filteroption',),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin approval for candidate profile'),
        ),
    ]
