# Generated by Django 6.0 on 2026-01-27 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0030_pendingfilteroption_candidate_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gap_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_gaps', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
