# Generated by Django 6.0 on 2026-01-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0031_careergap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='gap_reason',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='is_gap_period',
        ),
    ]
