# Generated by Django 6.0 on 2026-01-22 08:05

import apps.recruiters.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_remove_hrprofile_credits_balance_hrprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (PNG, JPG, JPEG only)', null=True, upload_to=apps.recruiters.models.company_logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('website', models.URLField(blank=True)),
                ('size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-1000', '201-1000 employees'), ('1000+', '1000+ employees')], max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='hrprofile',
            options={'verbose_name': 'HR Profile', 'verbose_name_plural': 'HR Profiles'},
        ),
        migrations.RemoveField(
            model_name='hrprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='hrprofile',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='hrprofile',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='hrprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='recruiters.company'),
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='recruiters.company')),
            ],
            options={
                'verbose_name': 'Company Location',
                'verbose_name_plural': 'Company Locations',
                'ordering': ['-is_headquarters', 'city'],
            },
        ),
    ]
