# Generated by Django 6.0 on 2026-01-22 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0024_hiringavailabilityui_content_vertical_alignment'),
        ('recruiters', '0003_company_alter_hrprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylocation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_city_locations', to='candidates.filteroption'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_country_locations', to='candidates.filteroption'),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_state_locations', to='candidates.filteroption'),
        ),
    ]
