# Generated by Django 6.0 on 2026-01-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_alter_companylocation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='HR profile verification status (separate from company verification)'),
        ),
    ]
