# Generated by Django 6.0 on 2026-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_add_hr_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_location',
            field=models.ManyToManyField(blank=True, related_name='company_locations', to='recruiters.companylocation'),
        ),
    ]
