# Generated by Django 6.0 on 2026-01-14 06:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(help_text='Version in format X.Y.Z (e.g., 1.0.0, 1.1.0)', max_length=20, validators=[django.core.validators.RegexValidator(message='Version must be in format X.Y.Z (e.g., 1.0.0)', regex='^\\d+\\.\\d+\\.\\d+$')])),
                ('version_code', models.PositiveIntegerField(help_text='Numeric version code for comparison (e.g., 100 for 1.0.0, 110 for 1.1.0)')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('BOTH', 'Both Platforms')], default='BOTH', max_length=10)),
                ('is_mandatory', models.BooleanField(default=False, help_text='If true, users must update to continue using the app')),
                ('is_active', models.BooleanField(default=True, help_text='Mark as active to make this the latest version')),
                ('minimum_supported_version', models.CharField(blank=True, help_text='Users below this version will be forced to update', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Version must be in format X.Y.Z (e.g., 1.0.0)', regex='^\\d+\\.\\d+\\.\\d+$')])),
                ('minimum_version_code', models.PositiveIntegerField(blank=True, help_text='Numeric code for minimum supported version', null=True)),
                ('release_notes', models.TextField(help_text="What's new in this version (shown to users)", max_length=1000)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this version was released')),
                ('download_url_android', models.URLField(blank=True, help_text='Play Store URL for Android', max_length=500, null=True)),
                ('download_url_ios', models.URLField(blank=True, help_text='App Store URL for iOS', max_length=500, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of new features in this version')),
                ('bug_fixes', models.JSONField(blank=True, default=list, help_text='List of bugs fixed in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'ordering': ['-version_code', '-created_at'],
                'unique_together': {('version_number', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='VersionCheckLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_version', models.CharField(max_length=20)),
                ('current_version_code', models.PositiveIntegerField()),
                ('platform', models.CharField(max_length=10)),
                ('update_available', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('force_update', models.BooleanField(default=False)),
                ('latest_version', models.CharField(blank=True, max_length=20, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version Check Log',
                'verbose_name_plural': 'Version Check Logs',
                'ordering': ['-checked_at'],
            },
        ),
    ]
