# Generated by Django 6.0 on 2026-01-17 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0002_remove_hrprofile_credits_balance_hrprofile_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Unlimited Monthly Plan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Plan description for admin reference')),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (3 Months)'), ('HALF_YEARLY', 'Half Yearly (6 Months)'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Plan price in rupees', max_digits=10)),
                ('is_unlimited', models.BooleanField(default=True, help_text='If true, company gets unlimited credits')),
                ('credits_limit', models.PositiveIntegerField(blank=True, help_text='Monthly credit limit (leave empty for unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active plans can be assigned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment transaction ID or reference', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Admin who cancelled this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('hr_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='recruiters.hrprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Company Subscription',
                'verbose_name_plural': 'Company Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVATED', 'Activated'), ('RENEWED', 'Renewed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('MODIFIED', 'Modified')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional action details')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.companysubscription')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ACTIVATED', 'Subscription Activated'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Subscription Expired'), ('CANCELLED', 'Subscription Cancelled'), ('RENEWED', 'Subscription Renewed')], max_length=20)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='subscriptions.companysubscription')),
            ],
            options={
                'verbose_name': 'Subscription Notification',
                'verbose_name_plural': 'Subscription Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['status', 'end_date'], name='subscriptio_status_337dad_idx'),
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['hr_profile', 'status'], name='subscriptio_hr_prof_237a74_idx'),
        ),
    ]
