# Generated by Django 6.0 on 2026-01-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionNotification',
        ),
    ]
