# Generated by Django 6.0 on 2026-01-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_credit', models.DecimalField(decimal_places=2, default=10.0, help_text='Price in rupees for 1 credit', max_digits=10)),
                ('unlock_credits_required', models.PositiveIntegerField(default=10, help_text='Number of credits required to unlock a candidate')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Settings',
                'verbose_name_plural': 'Credit Settings',
            },
        ),
    ]
