# Generated by Django 6.0 on 2026-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='recruiter_banners/')),
                ('height', models.PositiveIntegerField(default=250, help_text='Banner height in pixels')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recruiter Banner',
                'verbose_name_plural': 'Recruiter Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
