# Generated by Django 6.0 on 2026-01-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_recruiterbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterbanner',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
