# Generated by Django 6.0 on 2026-01-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_recruiterbanner_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterbanner',
            name='heading_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code (e.g., #FFFFFF)', max_length=9),
        ),
        migrations.AddField(
            model_name='recruiterbanner',
            name='heading_font_size',
            field=models.PositiveIntegerField(default=18, help_text='Font size in sp'),
        ),
        migrations.AddField(
            model_name='recruiterbanner',
            name='heading_font_weight',
            field=models.CharField(choices=[('300', 'Light'), ('400', 'Regular'), ('500', 'Medium'), ('600', 'Semi Bold'), ('700', 'Bold')], default='600', max_length=3),
        ),
        migrations.AddField(
            model_name='recruiterbanner',
            name='subheading_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code (e.g., #FFFFFF)', max_length=9),
        ),
        migrations.AddField(
            model_name='recruiterbanner',
            name='subheading_font_size',
            field=models.PositiveIntegerField(default=14, help_text='Font size in sp'),
        ),
        migrations.AddField(
            model_name='recruiterbanner',
            name='subheading_font_weight',
            field=models.CharField(choices=[('300', 'Light'), ('400', 'Regular'), ('500', 'Medium'), ('600', 'Semi Bold'), ('700', 'Bold')], default='400', max_length=3),
        ),
        migrations.AddField(
            model_name='recruiterbanner',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
    ]
