# Generated by Django 6.0 on 2026-01-12 06:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0015_alter_candidate_current_ctc_and_more'),
        ('recruiters', '0002_remove_hrprofile_credits_balance_hrprofile_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Admin reference name', max_length=200)),
                ('notification_type', models.CharField(choices=[('COMPLETE_PROFILE', 'Complete Profile'), ('PROFILE_STEP_REMINDER', 'Profile Step Reminder'), ('CANDIDATE_HIRED', 'Candidate Hired'), ('PROFILE_UPGRADE', 'Profile Upgrade'), ('GENERAL', 'General Announcement'), ('WELCOME', 'Welcome Message'), ('CREDIT_UPDATE', 'Credit Update')], max_length=30)),
                ('recipient_type', models.CharField(choices=[('CANDIDATE', 'Candidates Only'), ('HR', 'HR/Recruiters Only'), ('ALL', 'All Users')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_trigger', models.BooleanField(default=False, help_text='Auto send based on user actions')),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='Delay before sending (in minutes)')),
                ('play_sound', models.BooleanField(default=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notification_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active - Looking for Job'), ('HIRED', 'Hired'), ('ON_HOLD', 'Application on Hold'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn Application')], default='ACTIVE', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('position_title', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_status', to='candidates.candidate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiters.hrprofile')),
            ],
            options={
                'ordering': ['-status_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileStepReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('last_step_completed_at', models.DateTimeField(auto_now_add=True)),
                ('first_reminder_sent', models.BooleanField(default=False)),
                ('first_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('second_reminder_sent', models.BooleanField(default=False)),
                ('second_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('final_reminder_sent', models.BooleanField(default=False)),
                ('final_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_reminder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('fcm_message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('data_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=20)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('FCM_SENT', 'FCM Message Sent'), ('FCM_ERROR', 'FCM Error'), ('TEMPLATE_TRIGGERED', 'Template Triggered'), ('REMINDER_SCHEDULED', 'Reminder Scheduled'), ('USER_ACTION', 'User Action Triggered')], max_length=30)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.usernotification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
