# Generated by Django 6.0 on 2026-01-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='notification_icons/'),
        ),
    ]
