# Generated by Django 6.0 on 2026-01-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notificationtemplate_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('COMPLETE_PROFILE', 'Complete Profile'), ('PROFILE_STEP_REMINDER', 'Profile Step Reminder'), ('CANDIDATE_HIRED', 'Candidate Hired'), ('PROFILE_UPGRADE', 'Profile Upgrade'), ('GENERAL', 'General Announcement'), ('WELCOME', 'Welcome Message'), ('CREDIT_UPDATE', 'Credit Update'), ('CANDIDATE_REGISTERED', 'Candidate Registered'), ('FOLLOWUP_REMINDER', 'Follow-up Reminder')], max_length=30),
        ),
    ]
