# Generated by Django 6.0 on 2026-01-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationtemplate_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepNotificationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(unique=True)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('delay_hours', models.PositiveIntegerField(help_text='Delay in hours before sending notification')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Step Notification Detail',
                'verbose_name_plural': 'Step Notification Details',
                'ordering': ['step_number'],
            },
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step1_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step1_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step1_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step2_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step2_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step2_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step3_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step3_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step3_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step4_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step4_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilestepreminder',
            name='step4_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
