# Generated by Django 6.0 on 2026-01-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationtemplate_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('COMPLETE_PROFILE', 'Complete Profile'), ('PROFILE_STEP_REMINDER', 'Profile Step Reminder'), ('CANDIDATE_HIRED', 'Candidate Hired'), ('PROFILE_UPGRADE', 'Profile Upgrade'), ('GENERAL', 'General Announcement'), ('WELCOME', 'Welcome Message'), ('CREDIT_UPDATE', 'Credit Update'), ('CANDIDATE_REGISTERED', 'Candidate Registered'), ('FOLLOWUP_REMINDER', 'Follow-up Reminder'), ('AVAILABILITY_REMINDER', 'Availability Reminder'), ('SUBSCRIPTION_ACTIVATED', 'Subscription Activated'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring Soon'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('SUBSCRIPTION_CANCELLED', 'Subscription Cancelled')], max_length=30),
        ),
    ]
